# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

deals = [{:Restaurant => "Walter's 303 pizzaria and publik house", :ID => 'walters-303-pizzaria-and-publik-house-colorado-springs', :Deal_Title => '14% Off', :Offer_Code => 'PCTOFF1', :Exp_Date => '6/15/18', :Description => '14% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => '719 Gastropub', :ID => '719-gastropub-colorado-springs-2', :Deal_Title => '15% Off', :Offer_Code => 'PCTOFF2', :Exp_Date => '6/15/18', :Description => '15% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Dog Haus Biergarten', :ID => 'dog-haus-biergarten-colorado-springs-2', :Deal_Title => '16% Off', :Offer_Code => 'PCTOFF3', :Exp_Date => '6/15/18', :Description => '16% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Sushi Ato', :ID => 'sushi-ato-colorado-springs-2', :Deal_Title => '14% Off', :Offer_Code => 'PCTOFF4', :Exp_Date => '6/15/18', :Description => '14% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Bourbon Brothers Smokehouse and Tavern', :ID => 'bourbon-brothers-smokehouse-and-tavern-colorado-springs-2', :Deal_Title => '13% Off', :Offer_Code => 'PCTOFF5', :Exp_Date => '6/15/18', :Description => '13% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => "Duca's Neapolitan Pizza", :ID => 'ducas-neapolitan-pizza-colorado-springs', :Deal_Title => '12% Off', :Offer_Code => 'PCTOFF6', :Exp_Date => '6/15/18', :Description => '12% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Don Tequila Mexican Grill & Cantina', :ID => 'don-tequila-mexican-grill-and-cantina-monument-2', :Deal_Title => '12% Off', :Offer_Code => 'PCTOFF7', :Exp_Date => '6/15/18', :Description => '12% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => "Ivy's Chinese Cafe", :ID => 'ivys-chinese-cafe-colorado-springs', :Deal_Title => '18% Off', :Offer_Code => 'PCTOFF8', :Exp_Date => '6/15/18', :Description => '18% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Indus Modern Kitchen Express Indian Cuisine', :ID => 'indus-modern-kitchen-express-indian-cuisine-colorado-springs', :Deal_Title => '13% Off', :Offer_Code => 'PCTOFF9', :Exp_Date => '6/15/18', :Description => '13% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Modern Market Eatery', :ID => 'modern-market-eatery-colorado-springs', :Deal_Title => '14% Off', :Offer_Code => 'PCTOFF10', :Exp_Date => '6/15/18', :Description => '14% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Shri Ganesh', :ID => 'shri-ganesh-colorado-springs', :Deal_Title => '15% Off', :Offer_Code => 'PCTOFF11', :Exp_Date => '6/15/18', :Description => '15% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Cafe Velo', :ID => 'cafe-velo-colorado-springs-5', :Deal_Title => '13% Off', :Offer_Code => 'PCTOFF12', :Exp_Date => '6/15/18', :Description => '13% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Mikado Asian Bistro', :ID => 'mikado-asian-bistro-colorado-springs', :Deal_Title => '16% Off', :Offer_Code => 'PCTOFF13', :Exp_Date => '6/15/18', :Description => '16% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Thai Mint', :ID => 'thai-mint-colorado-springs', :Deal_Title => '11% Off', :Offer_Code => 'PCTOFF14', :Exp_Date => '6/15/18', :Description => '11% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Colorado Mountain Brewery', :ID => 'colorado-mountain-brewery-colorado-springs-3', :Deal_Title => '19% Off', :Offer_Code => 'PCTOFF15', :Exp_Date => '6/15/18', :Description => '19% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'The Brass Tap', :ID => 'the-brass-tap-colorado-springs', :Deal_Title => '18% Off', :Offer_Code => 'PCTOFF16', :Exp_Date => '6/15/18', :Description => '18% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Arabian Nights Cafe', :ID => 'arabian-nights-cafe-colorado-springs-2', :Deal_Title => '17% Off', :Offer_Code => 'PCTOFF17', :Exp_Date => '6/15/18', :Description => '17% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => "Cheddar's Casual Café", :ID => 'cheddars-casual-café-colorado-springs-5', :Deal_Title => '17% Off', :Offer_Code => 'PCTOFF18', :Exp_Date => '6/15/18', :Description => '17% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'CB & Potts', :ID => 'cb-and-potts-colorado-springs', :Deal_Title => '15% Off', :Offer_Code => 'PCTOFF19', :Exp_Date => '6/15/18', :Description => '15% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Happy Time Korean Restaurant', :ID => 'happy-time-korean-restaurant-colorado-springs', :Deal_Title => '14% Off', :Offer_Code => 'PCTOFF20', :Exp_Date => '6/15/18', :Description => '14% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => "Bad Daddy's Burger Bar", :ID => 'bad-daddys-burger-bar-colorado-springs-3', :Deal_Title => '16% Off', :Offer_Code => 'PCTOFF21', :Exp_Date => '6/15/18', :Description => '16% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Zoup!', :ID => 'zoup-colorado-springs', :Deal_Title => '19% Off', :Offer_Code => 'PCTOFF22', :Exp_Date => '6/15/18', :Description => '19% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Mountain View Cafe', :ID => 'mountain-view-cafe-colorado-springs', :Deal_Title => '17% Off', :Offer_Code => 'PCTOFF23', :Exp_Date => '6/15/18', :Description => '17% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Donuts & Noodle Vietnamese Asian Cuisine', :ID => 'donuts-and-noodle-colorado-springs', :Deal_Title => '14% Off', :Offer_Code => 'PCTOFF24', :Exp_Date => '6/15/18', :Description => '14% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => "Descar's Roadside Bar & Grill", :ID => 'descars-roadside-bar-and-grill-colorado-springs', :Deal_Title => '19% Off', :Offer_Code => 'PCTOFF25', :Exp_Date => '6/15/18', :Description => '19% off any purchase', :Restrictions => 'Only valid for one purchase'},
         {:Restaurant => 'Shots Coffee', :ID => 'shots-coffee-colorado-springs-2', :Deal_Title => '15% Off', :Offer_Code => 'PCTOFF26', :Exp_Date => '6/15/18', :Description => '15% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => "Rosie's Diner", :ID => 'rosies-diner-monument', :Deal_Title => '10% Off', :Offer_Code => 'PCTOFF27', :Exp_Date => '6/15/18', :Description => '10% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'The Steakhouse at Flying Horse', :ID => 'the-steakhouse-at-flying-horse-colorado-springs-2', :Deal_Title => '12% Off', :Offer_Code => 'PCTOFF28', :Exp_Date => '6/15/18', :Description => '12% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Costa Vida Fresh Mexican Grill', :ID => 'costa-vida-fresh-mexican-grill-colorado-springs', :Deal_Title => '10% Off', :Offer_Code => 'PCTOFF29', :Exp_Date => '6/15/18', :Description => '10% off any purchase', :Restrictions => 'Only valid for one purchase'},
         {:Restaurant => 'El Padrino Mexicano', :ID => 'el-padrino-mexicano-colorado-springs-3', :Deal_Title => '16% Off', :Offer_Code => 'PCTOFF30', :Exp_Date => '6/15/18', :Description => '16% off any purchase', :Restrictions => 'Only valid for one purchase'},
         {:Restaurant => "Ted's Montana Grill", :ID => 'teds-montana-grill-colorado-springs', :Deal_Title => '19% Off', :Offer_Code => 'PCTOFF31', :Exp_Date => '6/15/18', :Description => '19% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => "Tao's Oriental Cuisine", :ID => 'taos-oriental-cuisine-colorado-springs', :Deal_Title => '16% Off', :Offer_Code => 'PCTOFF32', :Exp_Date => '6/15/18', :Description => '16% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Broken Bones BBQ', :ID => 'broken-bones-bbq-colorado-springs', :Deal_Title => '15% Off', :Offer_Code => 'PCTOFF33', :Exp_Date => '6/15/18', :Description => '15% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'TILL Kitchen', :ID => 'till-kitchen-colorado-springs-2', :Deal_Title => '10% Off', :Offer_Code => 'PCTOFF34', :Exp_Date => '6/15/18', :Description => '10% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'The Bistro On 2nd', :ID => 'the-bistro-on-2nd-monument', :Deal_Title => '19% Off', :Offer_Code => 'PCTOFF35', :Exp_Date => '6/15/18', :Description => '19% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Kneaders Bakery & Cafe', :ID => 'kneaders-bakery-and-cafe-colorado-springs-2', :Deal_Title => '13% Off', :Offer_Code => 'PCTOFF36', :Exp_Date => '6/15/18', :Description => '13% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'R & R Coffee Cafe', :ID => 'r-and-r-coffee-cafe-colorado-springs', :Deal_Title => '15% Off', :Offer_Code => 'PCTOFF37', :Exp_Date => '6/15/18', :Description => '15% off any purchase', :Restrictions => 'Only valid for one purchase'},
         {:Restaurant => "King's Kitchen", :ID => 'kings-kitchen-colorado-springs', :Deal_Title => '19% Off', :Offer_Code => 'PCTOFF38', :Exp_Date => '6/15/18', :Description => '19% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Greek Cafe', :ID => 'greek-cafe-colorado-springs-2', :Deal_Title => '18% Off', :Offer_Code => 'PCTOFF39', :Exp_Date => '6/15/18', :Description => '18% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => "Freddy's Frozen Custard & Steakburgers", :ID => 'freddys-frozen-custard-and-steakburgers-colorado-springs-3', :Deal_Title => '12% Off', :Offer_Code => 'PCTOFF40', :Exp_Date => '6/15/18', :Description => '12% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Salsa Brava Fresh Mexican Grill', :ID => 'salsa-brava-fresh-mexican-grill-colorado-springs-2', :Deal_Title => '15% Off', :Offer_Code => 'PCTOFF41', :Exp_Date => '6/15/18', :Description => '15% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Mission Coffee Roasters', :ID => 'mission-coffee-roasters-colorado-springs-2', :Deal_Title => '10% Off', :Offer_Code => 'PCTOFF42', :Exp_Date => '6/15/18', :Description => '10% off any purchase', :Restrictions => 'Only valid for one purchase'},
         {:Restaurant => 'Broken Bones BBQ', :ID => 'broken-bones-bbq-monument-5', :Deal_Title => '11% Off', :Offer_Code => 'PCTOFF43', :Exp_Date => '6/15/18', :Description => '11% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Bird Dog BBQ', :ID => 'bird-dog-bbq-colorado-springs-2', :Deal_Title => '10% Off', :Offer_Code => 'PCTOFF44', :Exp_Date => '6/15/18', :Description => '10% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => "Drifter's Hamburgers", :ID => 'drifters-hamburgers-colorado-springs-2', :Deal_Title => '19% Off', :Offer_Code => 'PCTOFF45', :Exp_Date => '6/15/18', :Description => '19% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Back East Bar and Grill', :ID => 'back-east-bar-and-grill-colorado-springs', :Deal_Title => '12% Off', :Offer_Code => 'PCTOFF46', :Exp_Date => '6/15/18', :Description => '12% off any purchase', :Restrictions => 'Only valid for one purchase'},
         {:Restaurant => 'Black Forest Pies and Grinders', :ID => 'black-forest-pies-and-grinders-colorado-springs-2', :Deal_Title => '19% Off', :Offer_Code => 'PCTOFF47', :Exp_Date => '6/15/18', :Description => '19% off any purchase', :Restrictions => 'Only valid for one purchase'},
         {:Restaurant => 'Texas Roadhouse', :ID => 'texas-roadhouse-monument', :Deal_Title => '17% Off', :Offer_Code => 'PCTOFF48', :Exp_Date => '6/15/18', :Description => '17% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'Jasmine Garden', :ID => 'jasmine-garden-monument', :Deal_Title => '18% Off', :Offer_Code => 'PCTOFF49', :Exp_Date => '6/15/18', :Description => '18% off any purchase', :Restrictions => 'Only valid for one purchase'}, 
         {:Restaurant => 'The Egg & I', :ID => 'the-egg-and-i-colorado-springs-4', :Deal_Title => '19% Off', :Offer_Code => 'PCTOFF50', :Exp_Date => '6/15/18', :Description => '19% off any purchase', :Restrictions => 'Only valid for one purchase'}
        ]
        

deals.each do |deal|
    Deal.create!(deal)
end